server:
  port: 8083
  servlet:
    context-path: /images

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${RABBITMQ_USER:pica}"
    password: "${RABBITMQ_PASS:Pica2020++}"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IMAGES_COMMAND_HOST:localhost}:3303/imagescommandb
    username: image
    password: image2020++

events:
  amqp:
    exchange: images-exchange-events
    queue: images-queue-command
    routing-key: images-command-key
  dead-letter:
    exchange: images-exchange-deadletter
    queue: images-queue-deadletter
    routing-key: images-deadletter-key

images:
  resources:
    protocole: http
    port: 8083
    url: ${images.resources.protocole}://%s:${images.resources.port}/images/resources/load/%s
  files:
    upload:
      #directory: /tmp/upload/
      directory: c:\tmp\upload\

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.springframework.amqp: DEBUG
    co.edu.javeriana.images: DEBUG
